(defun my-open-file-with-app (file-path &optional open-explore-dir)
  "open the file-path by application associated it's file suffix or Windows explore."
  ;; *important* Do not check file-exist-p, because return nil even if actual file exists
  ;;   refer
  ;;   consult-file-externally in consult
  ;;   https://sakashushu.blog.ss-blog.jp/2014-04-29 "体当たり開始"
  (interactive "fFile-path: ")
  (cond ((eq (window-system) 'w32)
	 (cond ((file-directory-p file-path)
		(if open-explore-dir
		    ;; (w32-shell-execute "explore" file-path "/e,/select,")
		    ;; this can open folder in which has Japanese character
		    ;; but sometimes makes Windows Emacs freeze, use following

		    (w32-shell-execute nil file-path) ; nil see help
		  ;; monitor if this doesn't make Emacs freeze

		  ;;(async-shell-command (format "%s \"%s\"" "xstart" file-path) nil nil)
		  ;; this pop-up *Async Shell Command* buffer, not good

		  ;; https://stackoverflow.com/a/22982525
		  ;; this can't open directory if directory name has multi byte. e.g. Japanese character
		  ;;(call-process-shell-command (format "%s \"%s\"" "xstart" file-path) nil 0)
		  (find-file file-path)))
	       ((not (file-name-extension file-path))
		;; add this clause, because without suffix such as "tako" ".emacs" have an error on next condition
		;; member-ignore-case have Wrong type argument: stringp, nil
		(find-file file-path))
	       ((member-ignore-case (file-name-extension file-path) (append '("pdf" "gdoc") (my-open-file-with-app-extestions))) ; pdf, gdoc is not in assoc
		;; Since windows 8.1, (w32-shell-execute "open" file-name) is not available in case of "MOV", "mp4"

		;;(shell-command-to-string (format "%s %s" "start" file-path)) ; use the following
		;;(shell-command-to-string (string-join `("start" ,file-path) " "))

		;; But if there is space in file name, can't open the file with associated program, neither (shell-quote-argument file-name)
		;; need to modify "start" script then put ~/.config/fish/functions/xstart
		;;(shell-command-to-string (format "%s \"%s\"" "xstart" file-path))

		;; On Windows 10, w32-shell-execute has no problem
		(w32-shell-execute "open" file-path))
	       (t
		(find-file file-path))
	       ))
	(t
	 find-file file-path)))

;; to open html file in share folder which is exported by org with browser on windows environment
(defun advice:w32-shell-execute-filter-args (args)
  (setcar (cdr args) (replace-regexp-in-string "/" "\\\\" (cadr args))) ; pass ("open" "path is replaced with '/'")
  args ; return args processed for w32-shell-execute function to execute
)

(advice-add 'w32-shell-execute
	    :filter-args
            'advice:w32-shell-execute-filter-args)

;; windows application association list of file suffix
;; you can get assoc.exe in command prompt
(defvar my-open-file-with-w32-assoc-list '(
			 ".1=creoFile"
			 ".10=creoFile"
			 ".100=creoFile"
			 ".101=creoFile"
			 ".102=creoFile"
			 ".103=creoFile"
			 ".104=creoFile"
			 ".105=creoFile"
			 ".106=creoFile"
			 ".107=creoFile"
			 ".108=creoFile"
			 ".109=creoFile"
			 ".11=creoFile"
			 ".110=creoFile"
			 ".111=creoFile"
			 ".112=creoFile"
			 ".113=creoFile"
			 ".114=creoFile"
			 ".115=creoFile"
			 ".116=creoFile"
			 ".117=creoFile"
			 ".118=creoFile"
			 ".119=creoFile"
			 ".12=creoFile"
			 ".120=creoFile"
			 ".121=creoFile"
			 ".122=creoFile"
			 ".124=creoFile"
			 ".125=creoFile"
			 ".126=creoFile"
			 ".127=creoFile"
			 ".128=creoFile"
			 ".129=creoFile"
			 ".13=creoFile"
			 ".130=creoFile"
			 ".131=creoFile"
			 ".132=creoFile"
			 ".133=creoFile"
			 ".134=creoFile"
			 ".135=creoFile"
			 ".136=creoFile"
			 ".137=creoFile"
			 ".138=creoFile"
			 ".139=creoFile"
			 ".14=creoFile"
			 ".140=creoFile"
			 ".141=creoFile"
			 ".142=creoFile"
			 ".143=creoFile"
			 ".144=creoFile"
			 ".145=creoFile"
			 ".146=creoFile"
			 ".147=creoFile"
			 ".148=creoFile"
			 ".149=creoFile"
			 ".15=creoFile"
			 ".150=creoFile"
			 ".151=creoFile"
			 ".152=creoFile"
			 ".153=creoFile"
			 ".154=creoFile"
			 ".155=creoFile"
			 ".156=creoFile"
			 ".157=creoFile"
			 ".158=creoFile"
			 ".159=creoFile"
			 ".16=creoFile"
			 ".160=creoFile"
			 ".161=creoFile"
			 ".162=creoFile"
			 ".163=creoFile"
			 ".164=creoFile"
			 ".165=creoFile"
			 ".166=creoFile"
			 ".167=creoFile"
			 ".168=creoFile"
			 ".169=creoFile"
			 ".17=creoFile"
			 ".170=creoFile"
			 ".171=creoFile"
			 ".172=creoFile"
			 ".173=creoFile"
			 ".174=creoFile"
			 ".175=creoFile"
			 ".176=creoFile"
			 ".177=creoFile"
			 ".178=creoFile"
			 ".179=creoFile"
			 ".18=creoFile"
			 ".180=creoFile"
			 ".181=creoFile"
			 ".182=creoFile"
			 ".183=creoFile"
			 ".184=creoFile"
			 ".185=creoFile"
			 ".186=creoFile"
			 ".187=creoFile"
			 ".188=creoFile"
			 ".189=creoFile"
			 ".19=creoFile"
			 ".190=creoFile"
			 ".191=creoFile"
			 ".192=creoFile"
			 ".193=creoFile"
			 ".194=creoFile"
			 ".195=creoFile"
			 ".196=creoFile"
			 ".197=creoFile"
			 ".198=creoFile"
			 ".199=creoFile"
			 ".2=creoFile"
			 ".20=creoFile"
			 ".200=creoFile"
			 ".201=creoFile"
			 ".202=creoFile"
			 ".203=creoFile"
			 ".204=creoFile"
			 ".205=creoFile"
			 ".206=creoFile"
			 ".207=creoFile"
			 ".208=creoFile"
			 ".209=creoFile"
			 ".21=creoFile"
			 ".210=creoFile"
			 ".211=creoFile"
			 ".212=creoFile"
			 ".213=creoFile"
			 ".214=creoFile"
			 ".215=creoFile"
			 ".216=creoFile"
			 ".217=creoFile"
			 ".218=creoFile"
			 ".219=creoFile"
			 ".22=creoFile"
			 ".220=creoFile"
			 ".221=creoFile"
			 ".222=creoFile"
			 ".223=creoFile"
			 ".224=creoFile"
			 ".225=creoFile"
			 ".226=creoFile"
			 ".227=creoFile"
			 ".228=creoFile"
			 ".229=creoFile"
			 ".23=creoFile"
			 ".230=creoFile"
			 ".231=creoFile"
			 ".232=creoFile"
			 ".233=creoFile"
			 ".234=creoFile"
			 ".235=creoFile"
			 ".236=creoFile"
			 ".237=creoFile"
			 ".238=creoFile"
			 ".239=creoFile"
			 ".24=creoFile"
			 ".240=creoFile"
			 ".241=creoFile"
			 ".242=creoFile"
			 ".243=creoFile"
			 ".244=creoFile"
			 ".245=creoFile"
			 ".246=creoFile"
			 ".247=creoFile"
			 ".248=creoFile"
			 ".249=creoFile"
			 ".25=creoFile"
			 ".250=creoFile"
			 ".26=creoFile"
			 ".27=creoFile"
			 ".28=creoFile"
			 ".29=creoFile"
			 ".3=creoFile"
			 ".30=creoFile"
			 ".31=creoFile"
			 ".32=creoFile"
			 ".33=creoFile"
			 ".34=creoFile"
			 ".35=creoFile"
			 ".36=creoFile"
			 ".37=creoFile"
			 ".38=creoFile"
			 ".386=vxdfile"
			 ".39=creoFile"
			 ".3g2=WMP11.AssocFile.3G2"
			 ".3gp=WMP11.AssocFile.3GP"
			 ".3gp2=WMP11.AssocFile.3G2"
			 ".3gpp=WMP11.AssocFile.3GP"
			 ".4=creoFile"
			 ".40=creoFile"
			 ".41=creoFile"
			 ".42=creoFile"
			 ".43=creoFile"
			 ".44=creoFile"
			 ".45=creoFile"
			 ".46=creoFile"
			 ".47=creoFile"
			 ".48=creoFile"
			 ".49=creoFile"
			 ".5=creoFile"
			 ".50=creoFile"
			 ".51=creoFile"
			 ".52=creoFile"
			 ".53=creoFile"
			 ".54=creoFile"
			 ".55=creoFile"
			 ".56=creoFile"
			 ".57=creoFile"
			 ".58=creoFile"
			 ".59=creoFile"
			 ".5vw=wireshark-capture-file"
			 ".6=creoFile"
			 ".60=creoFile"
			 ".61=creoFile"
			 ".62=creoFile"
			 ".63=creoFile"
			 ".64=creoFile"
			 ".65=creoFile"
			 ".66=creoFile"
			 ".67=creoFile"
			 ".68=creoFile"
			 ".69=creoFile"
			 ".7=creoFile"
			 ".70=creoFile"
			 ".71=creoFile"
			 ".72=creoFile"
			 ".73=creoFile"
			 ".74=creoFile"
			 ".75=creoFile"
			 ".76=creoFile"
			 ".77=creoFile"
			 ".78=creoFile"
			 ".79=creoFile"
			 ".8=creoFile"
			 ".80=creoFile"
			 ".81=creoFile"
			 ".82=creoFile"
			 ".83=creoFile"
			 ".84=creoFile"
			 ".85=creoFile"
			 ".86=creoFile"
			 ".87=creoFile"
			 ".88=creoFile"
			 ".89=creoFile"
			 ".9=creoFile"
			 ".90=creoFile"
			 ".91=creoFile"
			 ".92=creoFile"
			 ".93=creoFile"
			 ".94=creoFile"
			 ".95=creoFile"
			 ".96=creoFile"
			 ".97=creoFile"
			 ".98=creoFile"
			 ".99=creoFile"
			 ".a3x=AutoIt3XScript"
			 ".AAC=WMP11.AssocFile.ADTS"
			 ".accda=Access.ACCDAExtension.16"
			 ".accdb=Access.Application.16"
			 ".accdc=Access.ACCDCFile.16"
			 ".accde=Access.ACCDEFile.16"
			 ".accdr=Access.ACCDRFile.16"
			 ".accdt=Access.ACCDTFile.16"
			 ".accdu=Access.WizardUserDataFile.16"
			 ".accdw=Access.WebApplicationReference.16"
			 ".accft=Access.ACCFTFile.16"
			 ".accountpicture-ms=accountpicturefile"
			 ".acl=ACLFile"
			 ".acp=wireshark-capture-file"
			 ".ade=Access.ADEFile.16"
			 ".adn=Access.BlankProjectTemplate.16"
			 ".adp=Access.Project.16"
			 ".ADT=WMP11.AssocFile.ADTS"
			 ".ADTS=WMP11.AssocFile.ADTS"
			 ".afm=NXafmfile"
			 ".aif=WMP11.AssocFile.AIFF"
			 ".aifc=WMP11.AssocFile.AIFF"
			 ".aiff=WMP11.AssocFile.AIFF"
			 ".ani=anifile"
			 ".ankiaddon=anki.ankiaddon"
			 ".apc=wireshark-capture-file"
			 ".apkg=anki.apkg"
			 ".appcontent-ms=ApplicationContent"
			 ".application=Application.Manifest"
			 ".appref-ms=Application.Reference"
			 ".asa=aspfile"
			 ".asd=Word.AutoRecovery.8"
			 ".asf=WMP11.AssocFile.ASF"
			 ".asm=asmFile"
			 ".asp=aspfile"
			 ".asx=WMP11.AssocFile.ASX"
			 ".atc=wireshark-capture-file"
			 ".au=WMP11.AssocFile.AU"
			 ".au3=AutoIt3Script"
			 ".AUP=Audacity.Project"
			 ".AUP3=Audacity.Project"
			 ".avi=WMP11.AssocFile.AVI"
			 ".aw=AWFile"
			 ".bat=batfile"
			 ".bfr=wireshark-capture-file"
			 ".bkm=UG Bookmark"
			 ".blg=Diagnostic.Perfmon.Document"
			 ".bmp=Paint.Picture"
			 ".cab=CABFolder"
			 ".camp=campfile"
			 ".cat=CATFile"
			 ".cda=WMP11.AssocFile.CDA"
			 ".cdmp=cdmpfile"
			 ".cdx=aspfile"
			 ".cdxml=Microsoft.PowerShellCmdletDefinitionXML.1"
			 ".cer=CERFile"
			 ".chk=chkfile"
			 ".chm=chm.file"
			 ".cmd=cmdfile"
			 ".colpkg=anki.colpkg"
			 ".com=comfile"
			 ".compositefont=Windows.CompositeFont"
			 ".cpl=cplfile"
			 ".crl=CRLFile"
			 ".crt=CERFile"
			 ".crtx=CRTXFile"
			 ".css=CSSfile"
			 ".csv=Excel.CSV"
			 ".cur=curfile"
			 ".db=dbfile"
			 ".dctx=IMEDictionaryCompiler"
			 ".dctxc=IMEDictionaryCompiler"
			 ".dds=ddsfile"
			 ".der=CERFile"
			 ".desklink=CLSID\{9E56BE61-C50F-11CF-9A2C-00A0C90A90CE}"
			 ".deskthemepack=desktopthemepackfile"
			 ".det=Outlook.File.det.15"
			 ".dgm=dgmFile"
			 ".diagcab=Diagnostic.Cabinet"
			 ".diagcfg=Diagnostic.Config"
			 ".diagpkg=Diagnostic.Document"
			 ".dib=Paint.Picture"
			 ".dll=dllfile"
			 ".doc=Word.Document.8"
			 ".dochtml=wordhtmlfile"
			 ".docm=Word.DocumentMacroEnabled.12"
			 ".docmhtml=wordmhtmlfile"
			 ".docx=Word.Document.12"
			 ".docxml=wordxmlfile"
			 ".dot=Word.Template.8"
			 ".dothtml=wordhtmltemplate"
			 ".dotm=Word.TemplateMacroEnabled.12"
			 ".dotx=Word.Template.12"
			 ".dqy=dqyfile"
			 ".drv=drvfile"
			 ".drw=drwFile"
			 ".dsn=MSDASQL"
			 ".elm=ELMFile"
			 ".emf=emffile"
			 ".eml=Outlook.File.eml.15"
			 ".enc=wireshark-capture-file"
			 ".evt=evtfile"
			 ".evtx=evtxfile"
			 ".exe=exefile"
			 ".fb2k-component=foobar2000.FB2K-COMPONENT"
			 ".fdc=wireshark-capture-file"
			 ".fdm=Outlook.File.fdm.15"
			 ".fem=NXfemfile"
			 ".flac=WMP11.AssocFile.FLAC"
			 ".fon=fonfile"
			 ".frm=frmFile"
			 ".fth=foobar2000.FTH"
			 ".gcsx=GCSXFile"
			 ".gcx=GeomCaliperOnProEfile"
			 ".gif=giffile"
			 ".gitattributes=txtfile"
			 ".gitignore=txtfile"
			 ".gitmodules=txtfile"
			 ".glox=GLOXFile"
			 ".gmmp=gmmpfile"
			 ".gqsx=GQSXFile"
			 ".gra=MSGraph.Chart.8"
			 ".grp=MSProgramGroup"
			 ".grs=GripSourceFile"
			 ".hlp=hlpfile"
			 ".hol=Outlook.File.hol.15"
			 ".hta=htafile"
			 ".htm=htmlfile"
			 ".html=htmlfile"
			 ".hxa=MSHelp.hxa.2.5"
			 ".hxc=MSHelp.hxc.2.5"
			 ".hxd=MSHelp.hxd.2.5"
			 ".hxe=MSHelp.hxe.2.5"
			 ".hxf=MSHelp.hxf.2.5"
			 ".hxh=MSHelp.hxh.2.5"
			 ".hxi=MSHelp.hxi.2.5"
			 ".hxk=MSHelp.hxk.2.5"
			 ".hxq=MSHelp.hxq.2.5"
			 ".hxr=MSHelp.hxr.2.5"
			 ".hxs=MSHelp.hxs.2.5"
			 ".hxt=MSHelp.hxt.2.5"
			 ".hxv=MSHelp.hxv.2.5"
			 ".hxw=MSHelp.hxa.2.5"
			 ".icc=icmfile"
			 ".icl=IconLibraryFile"
			 ".icm=icmfile"
			 ".ico=icofile"
			 ".ics=Outlook.File.ics.15"
			 ".imesx=imesxfile"
			 ".img=Windows.IsoFile"
			 ".inf=inffile"
			 ".ini=inifile"
			 ".ipa=iTunes.ipa"
			 ".ipfix=wireshark-capture-file"
			 ".ipg=iTunes.ipg"
			 ".ipsw=iTunes.ipsw"
			 ".iqy=iqyfile"
			 ".iso=Windows.IsoFile"
			 ".itdb=iTunes.itdb"
			 ".ite=iTunes.ite"
			 ".itl=iTunes.itl"
			 ".itlp=iTunes.itlp"
			 ".itls=iTunes.itls"
			 ".itms=iTunes.itms"
			 ".itpc=iTunes.itpc"
			 ".jar=jarfile"
			 ".jfif=pjpegfile"
			 ".jnlp=JNLPFile"
			 ".Job=JobObject"
			 ".jod=Microsoft.Jet.OLEDB.4.0"
			 ".jpe=jpegfile"
			 ".jpeg=jpegfile"
			 ".jpg=jpegfile"
			 ".js=JSFile"
			 ".JSE=JSEFile"
			 ".jxr=wdpfile"
			 ".label=Label"
			 ".laccdb=Access.LockFile.16"
			 ".lay=layFile"
			 ".lcap=wireshark-capture-file"
			 ".ldb=Access.LockFile.16"
			 ".lex=LEXFile"
			 ".library-ms=LibraryFolder"
			 ".lnk=lnkfile"
			 ".log=txtfile"
			 ".m1v=WMP11.AssocFile.MPEG"
			 ".M2T=WMP11.AssocFile.M2TS"
			 ".M2TS=WMP11.AssocFile.M2TS"
			 ".M2V=WMP11.AssocFile.MPEG"
			 ".m3u=WMP11.AssocFile.m3u"
			 ".m4a=WMP11.AssocFile.M4A"
			 ".m4r=iTunes.m4r"
			 ".m4v=WMP11.AssocFile.MP4"
			 ".mad=Access.Shortcut.Module.1"
			 ".maf=Access.Shortcut.Form.1"
			 ".mag=Access.Shortcut.Diagram.1"
			 ".mam=Access.Shortcut.Macro.1"
			 ".mapimail=CLSID\{9E56BE60-C50F-11CF-9A2C-00A0C90A90CE}"
			 ".maq=Access.Shortcut.Query.1"
			 ".mar=Access.Shortcut.Report.1"
			 ".mas=Access.Shortcut.StoredProcedure.1"
			 ".mat=Access.Shortcut.Table.1"
			 ".mau=Access.Shortcut.Function.1"
			 ".mav=Access.Shortcut.View.1"
			 ".maw=Access.Shortcut.DataAccessPage.1"
			 ".mda=Access.Extension.16"
			 ".mdb=Access.MDBFile"
			 ".mdbhtml=accesshtmlfile"
			 ".mde=Access.MDEFile.16"
			 ".mdn=Access.BlankDatabaseTemplate.16"
			 ".mdt=Access.WizardDataFile.16"
			 ".mdw=Access.Workgroup.16"
			 ".mfg=mfgFile"
			 ".mht=mhtmlfile"
			 ".mhtml=mhtmlfile"
			 ".mid=WMP11.AssocFile.MIDI"
			 ".midi=WMP11.AssocFile.MIDI"
			 ".mk3d=WMP11.AssocFile.MK3D"
			 ".mka=WMP11.AssocFile.MKA"
			 ".mkv=WMP11.AssocFile.MKV"
			 ".mlc=LpkSetup.1"
			 ".MOD=WMP11.AssocFile.MPEG"
			 ".mov=WMP11.AssocFile.MOV"
			 ".mp2=WMP11.AssocFile.MP3"
			 ".mp2v=WMP11.AssocFile.MPEG"
			 ".mp3=WMP11.AssocFile.MP3"
			 ".mp4=WMP11.AssocFile.MP4"
			 ".mp4v=WMP11.AssocFile.MP4"
			 ".mpa=WMP11.AssocFile.MPEG"
			 ".mpe=WMP11.AssocFile.MPEG"
			 ".mpeg=WMP11.AssocFile.MPEG"
			 ".mpg=WMP11.AssocFile.MPEG"
			 ".mplog=wireshark-capture-file"
			 ".mpv2=WMP11.AssocFile.MPEG"
			 ".mrk=mrkFile"
			 ".ms-windows-store-license=WindowsStore.License"
			 ".msc=MSCFile"
			 ".msg=Outlook.File.msg.15"
			 ".msi=Msi.Package"
			 ".msp=Msi.Patch"
			 ".msrcincident=RemoteAssistance.1"
			 ".msstyles=msstylesfile"
			 ".msu=Microsoft.System.Update.1"
			 ".MTS=WMP11.AssocFile.M2TS"
			 ".mydocs=CLSID\{ECF03A32-103D-11d2-854D-006008059367}"
			 ".nfo=MSInfoFile"
			 ".nk2=Outlook.File.nk2.15"
			 ".nodoka=nodokafile"
			 ".nst=Outlook.File.nst.15"
			 ".ntar=wireshark-capture-file"
			 ".nxmurl=NXManager url"
			 ".nxplmxml=NXPLMXML File"
			 ".nxtcxml=NXTCXML File"
			 ".ocx=ocxfile"
			 ".odc=odcfile"
			 ".odccubefile=odccubefile"
			 ".odcdatabasefile=odcdatabasefile"
			 ".odcnewfile=odcnewfile"
			 ".odctablecollectionfile=odctablecollectionfile"
			 ".odctablefile=odctablefile"
			 ".odp=PowerPoint.OpenDocumentPresentation.12"
			 ".ods=Excel.OpenDocumentSpreadsheet.12"
			 ".odt=Word.OpenDocumentText.12"
			 ".ofs=Outlook.File.ofs.15"
			 ".oft=Outlook.File.oft.15"
			 ".ols=OfficeListShortcut"
			 ".one=OneNote.Section.1"
			 ".onepkg=OneNote.Package"
			 ".onetoc=OneNote.TableOfContents"
			 ".onetoc2=OneNote.TableOfContents.12"
			 ".opc=OPCFile"
			 ".oqy=oqyfile"
			 ".osdx=opensearchdescription"
			 ".ost=Outlook.File.ost.15"
			 ".otf=otffile"
			 ".otm=Outlook.File.otm.15"
			 ".out=wireshark-capture-file"
			 ".p10=P10File"
			 ".p12=PFXFile"
			 ".p7b=SPCFile"
			 ".p7c=certificate_wab_auto_file"
			 ".p7m=P7MFile"
			 ".p7r=P7RFile"
			 ".p7s=P7SFile"
			 ".pab=Outlook.File.pab.15"
			 ".partial=IE.AssocFile.PARTIAL"
			 ".pax=UGpalettefile"
			 ".pbk=pbkfile"
			 ".pbmp=AzIP.pbmp"
			 ".pcap=wireshark-capture-file"
			 ".pcapng=wireshark-capture-file"
			 ".pcast=iTunes.pcast"
			 ".pcb=PCBFile"
			 ".perfmoncfg=Diagnostic.Perfmon.Config"
			 ".pfile=AzIP.pfile"
			 ".pfm=pfmfile"
			 ".pfx=PFXFile"
			 ".pgif=AzIP.pgif"
			 ".pgiff=AzIP.pgiff"
			 ".pha=phaFile"
			 ".pif=piffile"
			 ".pjfif=AzIP.pjfif"
			 ".pjpe=AzIP.pjpe"
			 ".pjpeg=AzIP.pjpeg"
			 ".pjpg=AzIP.pjpg"
			 ".pklg=wireshark-capture-file"
			 ".pko=PKOFile"
			 ".pkt=wireshark-capture-file"
			 ".plmxml=Plmxml File"
			 ".pnf=pnffile"
			 ".png=pngfile"
			 ".pot=PowerPoint.Template.8"
			 ".pothtml=powerpointhtmltemplate"
			 ".potm=PowerPoint.TemplateMacroEnabled.12"
			 ".potx=PowerPoint.Template.12"
			 ".ppa=PowerPoint.Addin.8"
			 ".ppam=PowerPoint.Addin.12"
			 ".ppdf=AzIP.ppdf"
			 ".ppkg=Microsoft.ProvTool.Provisioning.1"
			 ".ppng=AzIP.ppng"
			 ".pps=PowerPoint.SlideShow.8"
			 ".ppsm=PowerPoint.SlideShowMacroEnabled.12"
			 ".ppsx=PowerPoint.SlideShow.12"
			 ".ppt=PowerPoint.Show.8"
			 ".ppthtml=powerpointhtmlfile"
			 ".pptm=PowerPoint.ShowMacroEnabled.12"
			 ".pptmhtml=powerpointmhtmlfile"
			 ".pptx=PowerPoint.Show.12"
			 ".pptxml=powerpointxmlfile"
			 ".prf=prffile"
			 ".printerExport=brmFile"
			 ".prt=UGpartfile"
			 ".ps1=Microsoft.PowerShellScript.1"
			 ".ps1xml=Microsoft.PowerShellXMLData.1"
			 ".psc1=Microsoft.PowerShellConsole.1"
			 ".psd1=Microsoft.PowerShellData.1"
			 ".psf=psfFile"
			 ".psm1=Microsoft.PowerShellModule.1"
			 ".pssc=Microsoft.PowerShellSessionConfiguration.1"
			 ".pst=Outlook.File.pst.15"
			 ".ptif=AzIP.ptif"
			 ".ptiff=AzIP.ptiff"
			 ".ptxt=AzIP.ptxt"
			 ".pub=Publisher.Document.16"
			 ".pubhtml=publisherhtmlfile"
			 ".pubmhtml=publishermhtmlfile"
			 ".pwz=PowerPoint.Wizard.8"
			 ".pxml=AzIP.pxml"
			 ".py=Python.File"
			 ".pyc=Python.CompiledFile"
			 ".pyd=Python.Extension"
			 ".pyo=Python.CompiledFile"
			 ".pyw=Python.NoConFile"
			 ".pyz=Python.ArchiveFile"
			 ".pyzw=Python.NoConArchiveFile"
			 ".qds=SavedDsQuery"
			 ".QTTabBarCommand=QTTabBarLib.CommandButtonFile"
			 ".QTTabGroup=QTTabBarLib.QGroupOpener"
			 ".que=SMSDataFile"
			 ".rat=ratfile"
			 ".RDP=RDP.File"
			 ".reg=regfile"
			 ".resmoncfg=Diagnostic.Resmon.Config"
			 ".rf5=wireshark-capture-file"
			 ".rgreceiver=Rgreceiver.File"
			 ".rle=rlefile"
			 ".rll=dllfile"
			 ".rmi=WMP11.AssocFile.MIDI"
			 ".rqy=rqyfile"
			 ".rtf=Word.RTF.8"
			 ".SCCM.VAppLauncher=SCCM.VAppLauncher"
			 ".scf=SHCmdFile"
			 ".scp=txtfile"
			 ".scr=scrfile"
			 ".sct=scriptletfile"
			 ".search-ms=SearchFolder"
			 ".searchConnector-ms=SearchConnectorFolder"
			 ".sec=secFile"
			 ".settingcontent-ms=SettingContent"
			 ".sfcache=RDBFileProperties.1"
			 ".sh=sh_auto_file"
			 ".sim=NXsimfile"
			 ".sldm=PowerPoint.SlideMacroEnabled.12"
			 ".sldx=PowerPoint.Slide.12"
			 ".slk=Excel.SLK"
			 ".snd=WMP11.AssocFile.AU"
			 ".snoop=wireshark-capture-file"
			 ".spc=SPCFile"
			 ".sst=CertificateStoreFile"
			 ".svg=svgfile"
			 ".syc=wireshark-capture-file"
			 ".symlink=.symlink"
			 ".sys=sysfile"
			 ".theme=themefile"
			 ".themepack=themepackfile"
			 ".thmx=OfficeTheme.12"
			 ".tif=TIFImage.Document"
			 ".tiff=TIFImage.Document"
			 ".tpc=wireshark-capture-file"
			 ".tr1=wireshark-capture-file"
			 ".trace=wireshark-capture-file"
			 ".trc=wireshark-capture-file"
			 ".TS=WMP11.AssocFile.TTS"
			 ".ttc=ttcfile"
			 ".ttf=ttffile"
			 ".TTS=WMP11.AssocFile.TTS"
			 ".txt=txtfile"
			 ".UDL=MSDASC"
			 ".ugmbkm=UGManager Bookmark"
			 ".ugmportal=ugmportalfile"
			 ".ugs=ugsimanfile"
			 ".URL=InternetShortcut"
			 ".uxdc=UXDCFILE"
			 ".VBE=VBEFile"
			 ".vbs=VBSFile"
			 ".vcf=Outlook.File.vcf.15"
			 ".vcs=Outlook.File.vcs.15"
			 ".vdw=VisioViewer.Viewer"
			 ".vdx=VisioViewer.Viewer"
			 ".vhd=Windows.VhdFile"
			 ".vhdpmem=Windows.VhdPmemFile"
			 ".vhdx=Windows.VhdFile"
			 ".vsd=VisioViewer.Viewer"
			 ".vsdm=VisioViewer.Viewer"
			 ".vsdx=VisioViewer.Viewer"
			 ".vss=VisioViewer.Viewer"
			 ".vssm=VisioViewer.Viewer"
			 ".vssx=VisioViewer.Viewer"
			 ".vst=VisioViewer.Viewer"
			 ".vstm=VisioViewer.Viewer"
			 ".vsto=bootstrap.vsto.1"
			 ".vstx=VisioViewer.Viewer"
			 ".vsx=VisioViewer.Viewer"
			 ".vtx=VisioViewer.Viewer"
			 ".vwr=wireshark-capture-file"
			 ".vxd=vxdfile"
			 ".wab=wab_auto_file"
			 ".wav=WMP11.AssocFile.WAV"
			 ".wax=WMP11.AssocFile.WAX"
			 ".wbcat=wbcatfile"
			 ".wbk=Word.Backup.8"
			 ".wbx=wbx"
			 ".wcx=wcxfile"
			 ".wdp=wdpfile"
			 ".webpnp=webpnpFile"
			 ".website=Microsoft.Website"
			 ".wiz=Word.Wizard.8"
			 ".wizhtml=accessthmltemplate"
			 ".wll=Word.Addin.8"
			 ".wm=WMP11.AssocFile.ASF"
			 ".wma=WMP11.AssocFile.WMA"
			 ".WMD=WMP11.AssocFile.WMD"
			 ".wmdb=WMP.WMDBFile"
			 ".wmf=wmffile"
			 ".WMS=WMP11.AssocFile.WMS"
			 ".wmv=WMP11.AssocFile.WMV"
			 ".wmx=WMP11.AssocFile.ASX"
			 ".wmz=WMP11.AssocFile.WMZ"
			 ".wpc=wireshark-capture-file"
			 ".wpl=WMP11.AssocFile.WPL"
			 ".wpz=wireshark-capture-file"
			 ".wsc=scriptletfile"
			 ".WSF=WSFFile"
			 ".WSH=WSHFile"
			 ".wtx=txtfile"
			 ".wvx=WMP11.AssocFile.WVX"
			 ".xaml=Windows.XamlDocument"
			 ".xbap=Windows.Xbap"
			 ".xevgenxml=XEV.GenericApp"
			 ".xht=xhtmlfile"
			 ".xhtml=xhtmlfile"
			 ".xla=Excel.Addin"
			 ".xlam=Excel.AddInMacroEnabled"
			 ".xlaunch=XLaunchFile"
			 ".xld=Excel.Dialog"
			 ".xlk=Excel.Backup"
			 ".xll=Excel.XLL"
			 ".xlm=Excel.Macrosheet"
			 ".xls=Excel.Sheet.8"
			 ".xlsb=Excel.SheetBinaryMacroEnabled.12"
			 ".xlshtml=Excelhtmlfile"
			 ".xlsm=Excel.SheetMacroEnabled.12"
			 ".xlsmhtml=excelmhtmlfile"
			 ".xlsx=Excel.Sheet.12"
			 ".xlt=Excel.Template.8"
			 ".xlthtml=Excelhtmltemplate"
			 ".xltm=Excel.TemplateMacroEnabled"
			 ".xltx=Excel.Template"
			 ".xlw=Excel.Workspace"
			 ".xlxml=Excelxmlss"
			 ".xml=xmlfile"
			 ".xrm-ms=MSSppLicenseFile"
			 ".xsl=xslfile"
			 ".ZFSendToTarget=CLSID\{888DCA60-FC0A-11CF-8F0F-00C04FD7D062}"
			 ".zip=CompressedFolder"))

(defun my-open-file-with-app-extestions ()
  (mapcar
   (lambda (x)
     (string-match "^\.\\(.*\\)=.*" x)
     (match-string 1 x))
   my-open-file-with-w32-assoc-list))

;;; the followings are deprecated
(defun my-open-file-with-app-get-file-name ()
  "to get UNC path from cursor line"
  (interactive)
  (let ((f (thing-at-point 'line)))
    (if (string-match "\\(\\([a-z]:\\|\\\\\\)[^>]+\\) *" f)
	(message "%s" (match-string 1 f))
      (message "not match")
      nil)))

;;; supported by slack emacs-jp
(defun my-open-file-with-app-path2explore (fpath)
  "convert UNC path to emacs internal path"
  (if fpath
      (progn
	(let ((regexps '(("/" . "\\\\")
			 ("/cygdrive/\\(.\\)" . "\\1:")))
	      (file-w32 fpath))
	  (dolist (find-repl regexps)
	    (setq file-w32 (replace-regexp-in-string
			    (car find-repl) (cdr find-repl)
			    file-w32 nil nil)))
	  ;;(message "%s" file-w32)
	  file-w32
	  ))))

(provide 'my-open-file-with-app)
